# Generated by Django 5.0.7 on 2026-09-30 13:00

import apps.content.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_production_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, PNG or WebP images are accepted.'), apps.content.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Use only supplied or officially approved logos.', null=True, upload_to='partners/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, PNG or WebP images are accepted.'), apps.content.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='author',
            field=models.CharField(default='Usao Community Library Initiative Team', max_length=200),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='cover',
            field=models.ImageField(blank=True, help_text='Uploaded cover image (preferred).', null=True, upload_to='updates/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, PNG or WebP images are accepted.'), apps.content.validators.validate_image_size]),
        ),
        migrations.AddIndex(
            model_name='galleryimage',
            index=models.Index(fields=['is_active', 'order'], name='content_gal_is_acti_b34559_idx'),
        ),
        migrations.AddIndex(
            model_name='impactstatistic',
            index=models.Index(fields=['is_active', 'order'], name='content_imp_is_acti_c18db1_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['is_active', 'order'], name='content_par_is_acti_3b293a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectupdate',
            index=models.Index(fields=['published', '-published_date'], name='content_pro_publish_92a5ab_idx'),
        ),
    ]
