from django.urls import path

from .views import (
    AdminContentOverviewView,
    AdminGalleryImageDetailView,
    AdminGalleryImageListView,
    AdminImpactStatisticDetailView,
    AdminImpactStatisticListView,
    AdminLoginView,
    AdminLogoutView,
    AdminMeView,
    AdminPartnerDetailView,
    AdminPartnerListView,
    AdminProjectUpdateDetailView,
    AdminProjectUpdateListView,
    ApiRootView,
    GalleryImageListView,
    ImpactStatisticListView,
    PartnerListView,
    ProjectUpdateDetailView,
    ProjectUpdateListView,
    ProjectView,
)

urlpatterns = [
    path("", ApiRootView.as_view(), name="api-root"),
    path("project/", ProjectView.as_view(), name="project"),
    path("partners/", PartnerListView.as_view(), name="partner-list"),
    path("updates/", ProjectUpdateListView.as_view(), name="update-list"),
    path("updates/<slug:slug>/", ProjectUpdateDetailView.as_view(), name="update-detail"),
    path("gallery/", GalleryImageListView.as_view(), name="gallery-list"),
    path("impact/", ImpactStatisticListView.as_view(), name="impact-list"),
    path("admin/login/", AdminLoginView.as_view(), name="admin-login"),
    path("admin/logout/", AdminLogoutView.as_view(), name="admin-logout"),
    path("admin/me/", AdminMeView.as_view(), name="admin-me"),
    path("admin/overview/", AdminContentOverviewView.as_view(), name="admin-overview"),
    path("admin/updates/", AdminProjectUpdateListView.as_view(), name="admin-update-list"),
    path("admin/updates/<int:pk>/", AdminProjectUpdateDetailView.as_view(), name="admin-update-detail"),
    path("admin/partners/", AdminPartnerListView.as_view(), name="admin-partner-list"),
    path("admin/partners/<int:pk>/", AdminPartnerDetailView.as_view(), name="admin-partner-detail"),
    path("admin/gallery/", AdminGalleryImageListView.as_view(), name="admin-gallery-list"),
    path("admin/gallery/<int:pk>/", AdminGalleryImageDetailView.as_view(), name="admin-gallery-detail"),
    path("admin/impact/", AdminImpactStatisticListView.as_view(), name="admin-impact-list"),
    path("admin/impact/<int:pk>/", AdminImpactStatisticDetailView.as_view(), name="admin-impact-detail"),
]
