#!/usr/bin/env bash
# UCReCENT — cPanel VPS safe deploy script
# Runs ON THE SERVER (via GitHub Actions SSH). Only touches ~/ucrecent/*.
# NEVER touches other domains' document roots, vhosts, or databases.
#
# Required on server (one-time setup, see docs/DEPLOY_CPANEL.md):
#   ~/ucrecent               -> git clone -b main https://github.com/Tyronekrt/UCReCENT.git
#   ~/virtualenv/ucrecent-api (cPanel "Setup Python App" for api.<domain>)
#   ~/nodevenv/ucrecent-frontend (cPanel "Setup Node.js App" for <domain>)
#   backend/.env             -> real production values (never in git)
#
# Env overrides (all optional, safe defaults):
#   APP_ROOT, BACKEND_DIR, FRONTEND_DIR, BACKUP_DIR
#   NEXT_PUBLIC_SITE_URL, NEXT_PUBLIC_API_URL (baked into Next.js build)
set -euo pipefail

APP_ROOT="${APP_ROOT:-$HOME/ucrecent}"
BACKEND_DIR="${BACKEND_DIR:-$APP_ROOT/backend}"
FRONTEND_DIR="${FRONTEND_DIR:-$APP_ROOT/frontend}"
BACKUP_DIR="${BACKUP_DIR:-$HOME/ucrecent-backups}"

echo "=== UCReCENT deploy ==="
echo "APP_ROOT=$APP_ROOT"
date -u

# --- 0. Safety: never run as root, never touch other domains ---
if [ "$(id -u)" -eq 0 ]; then
  echo "ERROR: do not run deploy as root. Run as the cPanel account user." >&2
  exit 1
fi
if [ ! -d "$APP_ROOT/.git" ]; then
  echo "ERROR: $APP_ROOT is not a git clone. See docs/DEPLOY_CPANEL.md one-time setup." >&2
  exit 1
fi

mkdir -p "$BACKUP_DIR"

# --- 1. Backup current backend .env (never overwrite it with git) ---
if [ -f "$BACKEND_DIR/.env" ]; then
  cp -a "$BACKEND_DIR/.env" "$BACKUP_DIR/backend.env.$(date +%F_%H%M%S).bak"
  echo "Backed up backend/.env"
else
  echo "WARNING: $BACKEND_DIR/.env missing — backend will fail to start until created."
fi

# --- 2. Pull latest main (only this repo dir) ---
cd "$APP_ROOT"
git fetch origin main
git reset --hard origin/main
git clean -fd -e backend/media -e backend/.env -e frontend/.env.local -e backend/staticfiles
echo "Checked out: $(git rev-parse --short HEAD) $(git log -1 --format=%s)"

# --- 3. Backend: Django ---
echo "--- backend ---"
# Activate cPanel Python virtualenv if present (created by "Setup Python App")
if [ -f "$HOME/virtualenv/ucrecent-api/bin/activate" ]; then
  # shellcheck disable=SC1091
  source "$HOME/virtualenv/ucrecent-api/bin/activate"
elif [ -f "$BACKEND_DIR/venv/bin/activate" ]; then
  # shellcheck disable=SC1091
  source "$BACKEND_DIR/venv/bin/activate"
fi

python --version
pip install -r "$BACKEND_DIR/requirements.txt"
python "$BACKEND_DIR/manage.py" check --deploy || {
  echo "Django --deploy checks failed (see above). Aborting before migrate."
  exit 1
}
python "$BACKEND_DIR/manage.py" migrate --noinput
python "$BACKEND_DIR/manage.py" collectstatic --noinput
# Seed is idempotent — safe to run, creates starter content only if empty
python "$BACKEND_DIR/manage.py" seed_initial_content || true

# Passenger restart for API app only (does NOT restart Apache / other domains)
mkdir -p "$BACKEND_DIR/tmp"
touch "$BACKEND_DIR/tmp/restart.txt"
if [ -f "$APP_ROOT/deploy/cpanel/passenger_wsgi.py" ]; then
  # Keep cPanel entrypoint in sync (Backend app root -> passenger_wsgi.py)
  cp -a "$APP_ROOT/deploy/cpanel/passenger_wsgi.py" "$BACKEND_DIR/passenger_wsgi.py"
  touch "$BACKEND_DIR/tmp/restart.txt"
fi
echo "Backend migrated + restart signalled."

# --- 4. Frontend: Next.js ---
echo "--- frontend ---"
# Activate cPanel Node venv if present (created by "Setup Node.js App")
if [ -f "$HOME/nodevenv/ucrecent-frontend/bin/activate" ]; then
  # shellcheck disable=SC1091
  source "$HOME/nodevenv/ucrecent-frontend/bin/activate"
fi
node --version
npm --version

cd "$FRONTEND_DIR"
# NEXT_PUBLIC_* are baked at build time — take from environment (GitHub Secrets),
# fall back to existing .env.local if present, never commit secrets.
if [ -n "${NEXT_PUBLIC_SITE_URL:-}" ] || [ -n "${NEXT_PUBLIC_API_URL:-}" ]; then
  {
    echo "# Generated by deploy $(date -u +%FT%TZ) — do not commit"
    [ -n "${NEXT_PUBLIC_SITE_URL:-}" ] && echo "NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}"
    [ -n "${NEXT_PUBLIC_API_URL:-}" ] && echo "NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}"
  } > .env.production.local
fi
npm ci
npm run build
# Passenger / Node app restart for frontend only
mkdir -p tmp
touch tmp/restart.txt
# Keep startup wrapper in sync if using cPanel Node app
if [ -f "$APP_ROOT/deploy/cpanel/frontend-app.js" ] && [ ! -f "$FRONTEND_DIR/app.js" ]; then
  cp -a "$APP_ROOT/deploy/cpanel/frontend-app.js" "$FRONTEND_DIR/app.js"
fi
echo "Frontend built + restart signalled."

# --- 5. Health check (non-fatal) ---
echo "--- health ---"
python "$BACKEND_DIR/manage.py" check || true
curl -fsS --max-time 15 http://127.0.0.1:8000/api/health/ || echo "WARN: backend health endpoint not reachable via 127.0.0.1:8000 (normal if Passenger uses a socket). Check https://api.<domain>/api/health/ in browser."
if command -v pm2 >/dev/null 2>&1; then pm2 list || true; fi

echo "=== deploy OK: $(git rev-parse --short HEAD) ==="
