# Generated by Django 5.0.7 on 2026-09-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_request_workflow'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', '-created_at'], name='enquiries_c_status_1664a7_idx'),
        ),
        migrations.AddIndex(
            model_name='supportrequest',
            index=models.Index(fields=['status', '-created_at'], name='enquiries_s_status_c92ede_idx'),
        ),
    ]
